version: 1

blocked_ip:
  - "10.1.1.1"
  - "10.1.1.2"
wait_time: 45

monitoring:
  - dns_name: "server.fritz.box"
    ip: "10.2.2.2"
    mac: "77:88:99:aa:bb:cc"
  - dns_name: "server.mydomain.local"
    ip: "10.2.2.2"
    mac: "77:88:99:aa:bb:cc"

from_mail: "from_name@mydoamin.local"
to_mail: "to_name@mydoamin.local"
enable_mail: <True/False>


