version: 1
own_ip: "10.1.1.1"
# own_mac: "11:22:33:44:55:66"
wait_time: 45

listening_name: 
  - "server.fritz.box"
  - "server.mydomain.local"
listening_ip: 
  - "10.2.2.2"
listening_mac: 
  - "77:88:99:aa:bb:cc"

from_mail: "from_name@mydoamin.local"
to_mail: "to_name@mydoamin.local"
enable_mail: <True/False>


